#!/usr/bin/env python
import string
import gmwbot
guess = gmwbot.binaryguesser(list('bcdef'))
items = [None] + list('abcdefg')
print ' ',
for j in range(len(items)):
    if items[j] is None:
        print '.',
    else:
        print items[j],
print
for i in range(len(items)):
    if items[i] is None:
        print '.',
    else:
        print items[i],
    for j in range(len(items)):
        try:
            g = guess(items[i], items[j])
        except ValueError:
            g = '!'
        except gmwbot.NoGuessError:
            g = '!'
        print g,
    print
