#!/usr/bin/env python
import sys
import gmwbot
import gmwbottest

app = gmwbottest.mockgmw(sys.stdout)
app.word = 'sable'
app.action = '../x/y/z'
gmw = gmwbot.gmwclient("http://www.example.com/a/b/c/d",
    gmwbottest.mockrequests(app).request)
print cmp(gmw, 'lunisolar')
print cmp(gmw, 'sable')
