#!/usr/bin/env python
import gmwbottest
def echo_method(environ, start_response):
    start_response("200 OK", [])
    yield environ['REQUEST_METHOD']
    yield '\n'
for method in ['GET', 'POST', 'TWIDDLE']:
    gmwbottest.dumpresponse_httplib(echo_method, method, "/")
    print
