#!/usr/bin/env python
from string import ascii_lowercase
import gmwbot

search = gmwbot.searcher(gmwbot.binaryguesser(list(ascii_lowercase)))
for x in search('quixotic', left='noid', right='ululate'):
    print x
