#!/usr/bin/env python
from string import ascii_lowercase
import gmwbot

search = gmwbot.delayedobst(
    list(ascii_lowercase),
    [1]*len(ascii_lowercase),
    [1]*(len(ascii_lowercase)+1)
    )
for x in search('r', left='m', right='t'):
    print x
print
for x in search('razzledazzle', left='m', right='t'):
    print x
print
for x in search('r', left='music', right='tattle'):
    print x
print
