#!/usr/bin/env python
import gmwbottest

def echo_query(environ, start_response):
    start_response("200 OK", [])
    yield environ['QUERY_STRING']
gmwbottest.dumpresponse(echo_query, "POST", "/",
    params={'a': 'foo', 'b': ['bar', 'snee']})
