#!/usr/bin/env python
import gmwbot

guesses = ['a','q','c','o']
guesses.reverse()
def mockg(left, right):
    if guesses:
        g = guesses[-1]
        del guesses[-1]
        return g
    else:
        raise gmwbot.NoGuessError((left,right))
for x in gmwbot.searcher(mockg)('m'):
    print x
