#!/usr/bin/env python
import gmwbot
import gmwbottest

form = gmwbot.htmlform('/action', 'GET',
    [
        ('text', 'loud', 'huzzah'),
        ('submit', None, 'Yes'),
        ('hidden', 'shy', 'a'),
    ])
def f(method, url, body=None, headers=None):
    print repr(method)
    print repr(url)
    print repr(body)
    if headers is not None:
        for k,v in headers.items:
            print repr(k) + ': ' + repr(v)
form.submit(f)
