#!/usr/bin/env python
import gmwbot
import gmwbottest

form = gmwbot.htmlform.fromstr("""\
<form action="/~pahk/dictionary/guess.cgi" method="post" name="myform">
<div align="center">What is your guess?
<input type="text" name="guess" size="15" maxlength="15">
<input type="submit" value="Guess">
<input type="submit" name="result" value="I give up! Tell me!" value="no">
</div>
<input type="hidden" name="by" value="joon">
<input type="hidden" name="date" value="">
<input type="hidden" name="starttime" value="">
</form>""")

for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = (typ,nam,'lunisolar')
gmw = gmwbottest.mockgmw()
gmw.time = 1234
gmwbottest.dumpresponse(gmw, *form.submit())
