#!/usr/bin/env python
import gmwbottest

def echo_headers(environ, start_response):
    start_response("200 OK", [])
    for k,v in environ.items():
        if k.startswith("HTTP_"):
            yield k[5:] + ': ' + v + '\n'
gmwbottest.dumpresponse(echo_headers, "POST", "/",
    "body body body",
    { 'header1': 'value1', 'header2': 'value2'})
