#!/usr/bin/env python
import gmwbot

search = gmwbot.obstsearcher(
    ['a','b','c'],
    [1,3,2],
    [4,5,1,3])
print 'a'
for x in search('a'):
    print x
print
print 'am'
for x in search('am'):
    print x
print
print 'd'
for x in search('d'):
    print x
