#!/usr/bin/env python
import gmwbot

words = [
    'aaa',
    'blimey',
    'dismay',
    'gaggle',
    'lackey',
    'orrery',
    'robot',
    'undulate',
    'zzz',
    ]
search = gmwbot.searcher(gmwbot.binaryguesser(words))
for word in [words[3], 'taco', words[0], words[-1]]:
    print 'Searching for', repr(word)
    for x in search(word):
        print x
    print
