#!/usr/bin/env python
import gmwbot

class cmpword(object):
    def __init__(self, word, callback):
        self._word = word
        self._callback = callback
    def __cmp__(self, other):
        self._callback(other)
        return cmp(self._word, other)
def p(x):
    print x
words = [
    'aaa',
    'blimey',
    'dismay',
    'gaggle',
    'lackey',
    'orrery',
    'robot',
    'undulate',
    'zzz',
    ]
search = gmwbot.binarysearcher(words)
for word in [words[3], 'taco', words[0], words[-1]]:
    print 'Searching for', repr(word)
    result = search(cmpword(word, p))
    print 'result:', result
    print
