#!/usr/bin/env python
import gmwbot
import gmwbottest

gmw = gmwbottest.mockgmw()
gmw.time = 1234
gmw.word = 'sable'

print 'init'
conn = gmwbottest.mockhttpconn(gmw)
conn.request("GET", "/")
reply = conn.getresponse().read()
print reply

print 'lunisolar'
form = gmwbot.htmlform.fromstr(reply)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'lunisolar'
conn.request(*form.submit())
reply = conn.getresponse().read()
print reply

print 'taco'
form = gmwbot.htmlform.fromstr(reply)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'taco'
conn.request(*form.submit())
reply = conn.getresponse().read()
print reply

print 'sable'
form = gmwbot.htmlform.fromstr(reply)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'sable'
conn.request(*form.submit())
reply = conn.getresponse().read()
print reply
