#!/usr/bin/env python
import gmwbot
import gmwbottest
import sys

gmw = gmwbottest.mockgmw(sys.stdout)
gmw.time = 1234
gmw.word = 'sable'

conn = gmwbottest.mockrequests(gmw)
reply = conn.request("GET", "/").content
print reply

form = gmwbot.htmlform.fromstr(reply)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'lunisolar'
reply = form.submit(conn.request).content
print reply

form = gmwbot.htmlform.fromstr(reply)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'taco'
reply = form.submit(conn.request).content
print reply

form = gmwbot.htmlform.fromstr(reply)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'sable'
reply = form.submit(conn.request).content
print reply
