#!/usr/bin/env python
from datetime import datetime
import gmwbot
import gmwbottest
import sys

gmw = gmwbottest.mockgmw(sys.stdout)
gmw.time = 1234
gmw.word = 'sable'
gmw.wordtime = datetime(2012,1,2,3,4)

conn = gmwbottest.mockrequests(gmw)
reply = conn.request("GET", "http://example.com/")
print reply.content

form = gmwbot.htmlform.fromstr(reply.content, baseurl=reply.url)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'lunisolar'
reply = form.submit(conn.request)
print reply.content

form = gmwbot.htmlform.fromstr(reply.content, baseurl=reply.url)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'taco'
reply = form.submit(conn.request)
print reply.content

form = gmwbot.htmlform.fromstr(reply.content, baseurl=reply.url)
for i,(typ,nam,val) in enumerate(form.controls):
    if nam == 'guess':
        form.controls[i] = typ,nam,'sable'
reply = form.submit(conn.request)
print reply.content
