#!/usr/bin/env python
import gmwbottest

def echo_environ(environ, start_response):
    items = environ.items()
    items.sort()
    start_response("200 OK", [])
    for hdr,val in items:
        if hdr not in ['wsgi.input', 'wsgi.errors']:
            yield hdr + ': ' + str(val) + '\n'
gmwbottest.dumpresponse_httplib(echo_environ, "GET", "/")
