#!/usr/bin/env python
import gmwbottest
def app(environ, start_response):
    start_response("200 OK", [('X-Header1', 'Value1'), ('X-Header2', 'Value2')])
    return ['abc', 'def\n']
gmwbottest.dumpresponse(app, "GET", "/")
