#!/usr/bin/env python
from string import ascii_lowercase
import gmwbot

one = gmwbot.binaryguesser(list(ascii_lowercase))
two = gmwbot.binaryguesser(
    [x+y for x in ascii_lowercase for y in ascii_lowercase])
search = gmwbot.searcher(one, two)

for x in search('q'):
    print x
print
for x in search('qu'):
    print x
print
for x in search('qui'):
    print x
print
