#!/usr/bin/env python
import gmwbottest
def app(environ, start_response):
    write = start_response("200 OK", [('X-Header1', 'Value1'), ('X-Header2', 'Value2')])
    write('abc')
    write('def\n')
    return []
conn = gmwbottest.mockhttpconn(app)
conn.request("GET", "/")
resp = conn.getresponse()
print resp.status, resp.reason
for hdr, val in resp.getheaders():
    print hdr + ':', val
print
print resp.read(),
