#!/usr/bin/env python
import gmwbottest
def app(environ, start_response):
    write = start_response("200 OK", [('X-Header1', 'Value1'), ('X-Header2', 'Value2')])
    write('abc')
    write('def\n')
    return []
gmwbottest.dumpresponse_httplib(app, "GET", "/")
