#!/usr/bin/env python
from string import ascii_lowercase
import gmwbot

words = list(ascii_lowercase)

g = gmwbot.obstguesser(words, [1]*len(words), [0]*(len(words)+1))
print g('p', 'r')
try:
    print g('p', 'q')
except gmwbot.NoGuessError, e:
    print type(e), e

g = gmwbot.obstguesser_sjtbot2(words, [1]*len(words), [0]*(len(words)+1))
print g('p', 'r')
try:
    print g('p', 'q')
except gmwbot.NoGuessError, e:
    print type(e), e
