#!/usr/bin/env python
import gmwbot
import gmwbottest
import sys

server = gmwbottest.mockgmw(sys.stdout)
server.word = 'rascal'
req = gmwbottest.mockrequests(server)
client = gmwbot.gmwclient('/', req.request)

words = []
with open('twl') as twl:
    for line in twl:
        words.append(line.rstrip())
search = gmwbot.binarysearcher(words)

result = search(gmwbottest.cmplog(client))
print 'result:', result
